apiVersion: apps/v1
kind: Deployment
metadata:
  name: truthgraph-backend
spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: truthgraph-backend

  template:
    metadata:
      labels:
        app: truthgraph-backend

    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: truthgraph-backend
          image: ghcr.io/dhootraghav/truthgraph-backend:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: NEO4J_ENABLED
              value: "false"

          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
